name: API Regression Tests

on:
  #手工点 Run workflow
  workflow_dispatch:
  #有代码 Push/Commit 到 main，自动执行
  push:
    branches:
      - main
  #有 PR 准备合并到 main，自动执行
  pull_request:
    branches:
      - main
  #定时跑02:00 跑
  # schedule:
  #   - cron: '0 2 * * *'
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Postman CLI
        run: sudo npm install -g postman-cli

      - name: Login to Postman
        run: postman login --with-api-key "${{ secrets.POSTMAN_API_KEY }}"
 
      - name: Run API Regression Tests 
        env:
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          postman collection run postman/API-Automation-Demo.postman_collection.json \
            --environment postman/QA_Test.postman_environment.json \
            --env-var "testPassword=$TEST_PASSWORD" \
            -r cli,html \
            --reporter-html-export reports/api-report.html

      
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-api-test-report
          path: reports/api-report.html
          
